title: The Joker Printer Reference
description: An information repo on The Forgotten Imp's V-Core 3 printer
theme: just-the-docs

url: https://exitalterego.github.io/thejoker

aux_links:
  File Repository: https://github.com/Exitalterego/thejoker
